### ISSUE TITLE
Video runs off the sides of the site when viewing on iOS

### ISSUE THREAD

**Issue by alecholmez** [alecholmez/cpt-website#4]
The video is expanding the width of the website when viewing on iOS since we are using the:
```css
.video {
    transform: scale(4,4)
}
```
function.
